[colors]
background = '#000000'
foreground = '#ffffff'

cursor_bg = '#ccff00'
cursor_fg = '#000000'
cursor_border = '#ccff00'

selection_bg = '#00ccff'
selection_fg = '#000000'

# compose_cursor = '#'

ansi = [
  '#000000',
  '#ff6633',
  '#ccff00',
  '#ffcc33',
  '#00ccff',
  '#cc99cc',
  '#00cccc',
  '#f9f9f9',
]

brights = [
  '#000000',
  '#ff6633',
  '#ccff00',
  '#ffcc33',
  '#00ccff',
  '#cc99cc',
  '#00cccc',
  '#f9f9f9',
]

[colors.indexed]

[colors.tab_bar]
background = '#333333'

[colors.tab_bar.active_tab]
bg_color = '#000000'
fg_color = '#ffffff'
intensity = 'Bold'

[colors.tab_bar.inactive_tab]
bg_color = '#333333'
fg_color = '#ffffff'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#000000'
fg_color = '#ffffff'
intensity = 'Bold'

[colors.tab_bar.new_tab]
bg_color = '#333333'
fg_color = '#ffffff'

[colors.tab_bar.new_tab_hover]
bg_color = '#000000'
fg_color = '#ffffff'

[metadata]
name = 'kalaclista'
origin_url = 'https://colors.kalaclista.com/'
